- src/settings/common.py
issue https://github.com/telefonicaid/orchestrator/issues/8
time
lvl
corr
trans
from
srv
subsrv
comp
op
msg
> align log format

- ChangeLog
- IOTMODULES.md
- docker-compose.yml
- src/orchestrator/core/flow/base.py
- src/orchestrator/core/startup.py
- src/settings/dev.py
Issue https://github.com/telefonicaid/orchestrator/issues/18
> Task/notify path by conf for iotmodules (release/1.2.0)

- ChangeLog
- setup.cfg
- src/orchestrator/api/views.py
issue https://github.com/telefonicaid/orchestrator/issues/24
> add ORION endpoint to flows for delete domain and project (release/1.2.0)

- src/orchestrator/core/perseo.py
https://github.com/telefonicaid/orchestrator/issues/16
> fix perseo API base url

- ChangeLog
- Dockerfile
- bin/orchestrator-entrypoint.sh
Fixes: https://github.com/telefonicaid/orchestrator/issues/42
> add notifypath to cygnus, perseo and sth in docker conf

- src/orchestrator/api/parsers.py
- src/orchestrator/api/views.py
- src/orchestrator/core/startup.py
Fix for https://github.com/telefonicaid/orchestrator/issues/52
> bugfix: add missed filters to django loggers

- requirements.txt
not enough for https://github.com/telefonicaid/orchestrator/issues/39
> minor updates for current django versions

- package-orchestrator.sh
To be invoked from jenkings CI with parameters
> added --with-version and --with-release options

- ChangeLog
- src/orchestrator/core/orion.py
Fix: https://github.com/telefonicaid/orchestrator/issues/37
> add pagination to deal with orion subscriptions

- ChangeLog
- setup.cfg
- sonar-project.properties
- src/orchestrator/core/flow/Projects.py
Fix for https://github.com/telefonicaid/orchestrator/issues/74
> Fix/get project with scoped token (release/1.4.0)

- src/orchestrator/core/flow/Projects.py
Fix: https://github.com/telefonicaid/orchestrator/issues/76
> domain_name_before_assignment (release/1.4.0)

- ChangeLog
- bin/orchestrator-entrypoint.sh
issue: https://github.com/telefonicaid/orchestrator/issues/78
> allow non positional args for orchestrator entrypoint

- ChangeLog
- bin/orchestrator-entrypoint.sh
https://github.com/telefonicaid/orchestrator/issues/82
> set pepperseo conf after perseo conf

- src/orchestrator/core/iota_cpp.py
using and old branch: iota logs were missed
> the same about level logs for iota

- ChangeLog
- src/orchestrator/api/views.py
minor bug
Just in reset metrics API
> fix typo in 204 status content

- CONFIG.md
- ChangeLog
- src/orchestrator/api/views.py
- src/orchestrator/core/flow/base.py
- src/settings/common.py
- src/tests/api/test_api.py
Issue: https://github.com/telefonicaid/orchestrator/issues/114
> add conf to enable or disable extended metrics

- apiary.apib
- src/orchestrator/api/ldap_view.py
- src/orchestrator/core/flow/LdapUserHelper.py
- src/orchestrator/core/openldap.py
- src/tests/api/test_ldap_api.py
reopen branch to add some fixes
https://github.com/telefonicaid/orchestrator/issues/120
> fix modify user group

- apiary.apib
- src/orchestrator/api/ldap_view.py
- src/tests/api/test_ldap_api.py
> fix delete response

- src/orchestrator/core/flow/LdapUserHelper.py
- src/orchestrator/core/openldap.py
reopen to fix search operation
> fix user search

- src/orchestrator/core/openldap.py
> fix member groups

- ChangeLog
- Dockerfile
- bin/orchestrator-entrypoint.sh
- src/orchestrator/core/flow/createTrustToken.py
- src/settings/dev.py
fix issue https://github.com/telefonicaid/orchestrator/issues/171
> add option to set default pep and iotagent pwd

- ChangeLog
- bin/orchestrator-entrypoint.sh
Fix issue https://github.com/telefonicaid/orchestrator/issues/175
> Handle cygnus_multiagent option

- ChangeLog
- requirements.txt
issue https://github.com/telefonicaid/orchestrator/issues/186
> upgrade django due to security vulnerability and other python deps

- ChangeLog
- src/orchestrator/core/flow/LdapUserHelper.py
Just add an extra check in a dict
> add an extra check ldap getUserDetailsByAdmin

- ChangeLog
- src/orchestrator/api/views.py
- src/orchestrator/core/flow/createNewService.py
- src/orchestrator/core/flow/createNewSubService.py
- src/orchestrator/core/mongo.py
fix issue https://github.com/telefonicaid/orchestrator/issues/192
> add sth mongodb indexes

- ChangeLog
- src/orchestrator/core/mongo.py
Aligned with recent changes in PR https://github.com/telefonicaid/fiware-orion/pull/3495
> Update Orion indexes creation logic

- ChangeLog
- Dockerfile
Future docker versions does not allow empty lines
> remove empty lines dockerfile

- ChangeLog
- requirements.txt
> remove httplib2 and simplejson deps

- src/orchestrator/core/flow/Roles.py
reopen previous PR https://github.com/telefonicaid/orchestrator/pull/228
> fix typo: replace SERVICE_USER_ID by SERVICE_GROUP_ID

- src/orchestrator/core/flow/createNewService.py
comes from https://github.com/telefonicaid/orchestrator/pull/228
> fix service customer group

- ChangeLog
- README.md
- apiary.apib
- src/orchestrator/api/ldap_view.py
- src/orchestrator/api/schemas.py
- src/orchestrator/api/urls.py
- src/orchestrator/core/flow/LdapGroupHelper.py
- src/orchestrator/core/openldap.py
fix issue https://github.com/telefonicaid/orchestrator/issues/235
- New APIs:
> API CRUD ldap groups

- src/orchestrator/core/flow/Domains.py
- src/orchestrator/core/flow/Projects.py
reopens https://github.com/telefonicaid/orchestrator/pull/233
> fix idPattern

- ChangeLog
- src/orchestrator/core/perseo.py
> Update perseo URL to affect all rules

- ChangeLog
- setup.cfg
- sonar-project.properties
Do not merge branch  release/3.1.0
> bump 3.1.0 version

- ChangeLog
- src/orchestrator/core/flow/Domains.py
- src/orchestrator/core/keystone.py
performance improvement aligned with https://github.com/telefonicaid/fiware-keystone-scim/pull/54
> remove all roles at once time 

- ChangeLog
- src/orchestrator/core/flow/createNewService.py
- src/orchestrator/core/keystone.py
performance improvement creating new service
> add op to create roles at once

- ChangeLog
- Dockerfile
- setup.cfg
- sonar-project.properties
> bump 3.4.0

- ChangeLog
- requirements.txt
Reverts telefonicaid/orchestrator#282
> Revert "upgrade django"

- ChangeLog
- src/orchestrator/core/flow/createNewService.py
fix issue https://github.com/telefonicaid/orchestrator/issues/287
> fix sth index for service

- ChangeLog
- src/orchestrator/api/schemas.py
fix issue https://github.com/telefonicaid/orchestrator/issues/285
> fix chars allowed in grant names and fix their length to 128

- ChangeLog
- Dockerfile
docker image build: https://hub.docker.com/repository/registry-1.docker.io/telefonicaiot/orchestrator/builds/a981cd57-66ab-4fba-8473-cc684c0a5997
> remove repoze.lru dep (not used )

- requirements.txt
suggested by @devops
https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.19.1.html
https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.19.html
> Update uwsgi version in requirements.txt

- ChangeLog
- requirements.txt
just to fix master build https://hub.docker.com/repository/registry-1.docker.io/telefonicaiot/orchestrator/builds/a144b910-9aec-4442-bfec-43b724732b36
> upgrade jsonschema

- ChangeLog
- src/orchestrator/core/policies/policy-sth-admin.xml
- src/orchestrator/core/policies/policy-sth-admin2.xml
- src/orchestrator/core/policies/policy-sth-customer.xml
- src/orchestrator/core/policies/policy-sth-customer2.xml
- src/orchestrator/core/policies/policy-sth-serviceadmin.xml
- src/orchestrator/core/policies/policy-sth-servicecustomer.xml
- src/orchestrator/core/policies/policy-sth-subserviceadmin.xml
- src/orchestrator/core/policies/policy-sth-subservicecustomer.xml
revert previious PR https://github.com/telefonicaid/orchestrator/pull/307
That policies are wrong; actions verbs from STH and CB are mixed and dening some CB access.
> restore to previoius sth policies

- ChangeLog
- Dockerfile
- setup.cfg
- sonar-project.properties
> bump 4.0.0

- ChangeLog
- src/settings/common.py
fix for a similar error https://github.com/kennethsn/django-wikidata-api/issues/2
related
> fix default render classes

- ChangeLog
- Dockerfile
- bin/orchestrator-entrypoint.sh
> dockerfile debian based

- ChangeLog
Related PR https://github.com/telefonicaid/orchestrator/pull/327
> FIX Changelog

- ChangeLog
- Dockerfile
- setup.cfg
- sonar-project.properties
> bump version 4.2.0

- ChangeLog
- src/orchestrator/core/mongo.py
> ADD new indexes for Orion

- ChangeLog
- requirements.txt
> Bump djangorestframework from 3.11.2 to 3.15.1

- ChangeLog
- Dockerfile
but 12.9 is comming: https://www.debian.org/News/2025/20250111
> Update Dockerfile: debian 12.9

- ChangeLog
- requirements.txt
> Upgrade pymongo dep

- CONFIG.md
- ChangeLog
- bin/orchestrator-daemon.sh
some improvements in doc related with https://github.com/telefonicaid/orchestrator/pull/375
> update doc about uwsgi stats

- Dockerfile
continuation https://github.com/telefonicaid/orchestrator/pull/375
> fix default ports in docker
